// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Acc_SubSubsidiaryLedger
{
    public decimal autoId { get; set; }

    public string SubsidiaryLedgerCodeNo { get; set; }

    public string SubSusidiaryLedgerCodeNo { get; set; }

    public string SubSubsidiaryLedgerName { get; set; }

    public string ShortName { get; set; }

    public decimal? OpeningBalance { get; set; }

    public string TrType { get; set; }

    public DateTime? OpeningDate { get; set; }

    public string IsActive { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CashFlowTypeID { get; set; }

    public string CostCenterCodeNo { get; set; }
}