// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Acc_SubsidiaryLedger
{
    public decimal autoId { get; set; }

    public string GeneralLedgerCodeNo { get; set; }

    public string SusidiaryLedgerCodeNo { get; set; }

    public string SubsidiaryLedgerName { get; set; }

    public string ShortName { get; set; }

    public string IsSameNameSL { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }
}