// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Acc_VoucherEntry
{
    public decimal autoId { get; set; }

    public string VoucherEntryCodeNo { get; set; }

    public string CostCenterCodeNo { get; set; }

    public string FinancialYear { get; set; }

    public string PeriodCodeNo { get; set; }

    public string VoucherType_Code { get; set; }

    public DateTime VoucherDate { get; set; }

    public string VoucherNo { get; set; }

    public string Narration { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string UserInfoEmployeeID { get; set; }

    public string Main_CompanyCode { get; set; }

    public string BranchCode { get; set; }

    public string DivisionCode { get; set; }

    public string InvoiceNo { get; set; }

    public string IsApproved { get; set; }

    public string ApprovedBy { get; set; }

    public DateTime? ApprovedDate { get; set; }
}