// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Acc_Company_Opening_Balance
{
    public decimal autoId { get; set; }

    public string ComOpeningBalanceCode { get; set; }

    public string Main_CompanyCode { get; set; }

    public string BranchCode { get; set; }

    public string SubSusidiaryLedgerCodeNo { get; set; }

    public decimal? OpeningBalance { get; set; }

    public string TrType { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string UserInfoEmployeeID { get; set; }
}