// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Acc_VoucherEntryDetails
{
    public decimal autoId { get; set; }

    public string VoucherEntryDetailsCodeNo { get; set; }

    public string VoucherEntryCodeNo { get; set; }

    public string AccCode { get; set; }

    public string TrType { get; set; }

    public string Description { get; set; }

    public decimal? DebitAmount { get; set; }

    public decimal? CreditAmount { get; set; }

    public string ChequeNo { get; set; }

    public DateTime? ChequeDate { get; set; }

    public string BankName { get; set; }

    public string Branch { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public decimal? VoucherEntryAutoID { get; set; }
}