// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ActionLogs
{
    public int ActionLogID { get; set; }

    public string UserEmail { get; set; }

    public string ActionName { get; set; }

    public string ActionBefore { get; set; }

    public string ActionAfter { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public string TargetType { get; set; }

    public int? TargetID { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }
}