// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ApprovalLevelAssignments
{
    public int ApprovalSettingID { get; set; }

    public int LevelNumber { get; set; }

    public int? ApproverEmployeeID { get; set; }

    public bool? IsEnabled { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual ApprovalSettings ApprovalSetting { get; set; }

    public virtual Employees ApproverEmployee { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}