// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ApprovalSettings
{
    public int ApprovalSettingID { get; set; }

    public int? OrganizationID { get; set; }

    public int? OrganizationBranchID { get; set; }

    public int? ApprovalTypeID { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public bool? AllowSelfApproval { get; set; }

    public int? SelfExceptionApprovalID { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual ICollection<ApprovalLevelAssignments> ApprovalLevelAssignments { get; set; } = new List<ApprovalLevelAssignments>();

    public virtual ApprovalTypes ApprovalType { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual OrganizationBranches OrganizationBranch { get; set; }

    public virtual Employees SelfExceptionApproval { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}