// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class AspNetUsers
{
    public string Id { get; set; }

    public string Discriminator { get; set; }

    public string FullName { get; set; }

    public byte? Gender { get; set; }

    public int? EmployeeId { get; set; }

    public string NIDNumber { get; set; }

    public string PresentAddress { get; set; }

    public string PermanentAddress { get; set; }

    public DateTime? CreatedDateTime { get; set; }

    public DateTime? UpdatedDateTime { get; set; }

    public DateTime? JoiningDate { get; set; }

    public DateTime? DateofBirth { get; set; }

    public string UserName { get; set; }

    public string NormalizedUserName { get; set; }

    public string Email { get; set; }

    public string NormalizedEmail { get; set; }

    public bool EmailConfirmed { get; set; }

    public string PasswordHash { get; set; }

    public string SecurityStamp { get; set; }

    public string ConcurrencyStamp { get; set; }

    public string PhoneNumber { get; set; }

    public bool PhoneNumberConfirmed { get; set; }

    public bool TwoFactorEnabled { get; set; }

    public DateTimeOffset? LockoutEnd { get; set; }

    public bool LockoutEnabled { get; set; }

    public int AccessFailedCount { get; set; }

    public int? OrganizationID { get; set; }

    public int? TenantInfoId { get; set; }

    public virtual ICollection<AspNetUserClaims> AspNetUserClaims { get; set; } = new List<AspNetUserClaims>();

    public virtual ICollection<AspNetUserLogins> AspNetUserLogins { get; set; } = new List<AspNetUserLogins>();

    public virtual ICollection<AspNetUserTokens> AspNetUserTokens { get; set; } = new List<AspNetUserTokens>();

    public virtual Employees Employee { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual TenantInfo TenantInfo { get; set; }

    public virtual ICollection<AspNetRoles> Role { get; set; } = new List<AspNetRoles>();
}