// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class AspNetRoles
{
    public string Id { get; set; }

    public string Discriminator { get; set; }

    public string Name { get; set; }

    public string NormalizedName { get; set; }

    public string ConcurrencyStamp { get; set; }

    public int? TenantInfoId { get; set; }

    public int? OrganizationID { get; set; }

    public virtual ICollection<AspNetRoleClaims> AspNetRoleClaims { get; set; } = new List<AspNetRoleClaims>();

    public virtual Organization Organization { get; set; }

    public virtual ICollection<RoleElementPermissions> RoleElementPermissions { get; set; } = new List<RoleElementPermissions>();

    public virtual ICollection<RoleModulePermissions> RoleModulePermissions { get; set; } = new List<RoleModulePermissions>();

    public virtual TenantInfo TenantInfo { get; set; }

    public virtual ICollection<AspNetUsers> User { get; set; } = new List<AspNetUsers>();
}