// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class AttributeValue
{
    public int AttributeValueID { get; set; }

    public int AttributeID { get; set; }

    public string Value { get; set; }

    public virtual AttributeDef Attribute { get; set; }

    public virtual ICollection<VariantAttribute> VariantAttribute { get; set; } = new List<VariantAttribute>();
}