// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class AttributeDef
{
    public int AttributeID { get; set; }

    public string AttributeName { get; set; }

    public virtual ICollection<AttributeValue> AttributeValue { get; set; } = new List<AttributeValue>();

    public virtual ICollection<VariantAttribute> VariantAttribute { get; set; } = new List<VariantAttribute>();
}