// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class BundleComponent
{
    public int BundleComponentID { get; set; }

    public int BundleProductID { get; set; }

    public int ComponentProdID { get; set; }

    public int? ComponentVariantID { get; set; }

    public decimal QtyPerBundle { get; set; }

    public virtual Product BundleProduct { get; set; }

    public virtual Product ComponentProd { get; set; }

    public virtual ProductVariant ComponentVariant { get; set; }
}