// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CA_Def_Currency
{
    public decimal TC { get; set; }

    public string CurrencyId { get; set; }

    public string CurrencyName { get; set; }

    public string ShortName { get; set; }

    public string Symbol { get; set; }

    public int? DecimalPlaces { get; set; }

    public string NegativeFormat { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }
}