// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CF_BillEntry
{
    public decimal TC { get; set; }

    public string BillNo { get; set; }

    public DateTime? BillDate { get; set; }

    public string JRSNo { get; set; }

    public string JobNo { get; set; }

    public string OFRNo { get; set; }

    public string ExpenseTypeID { get; set; }

    public string CustomerID { get; set; }

    public string Address { get; set; }

    public string MaterialDescription { get; set; }

    public string BLNo { get; set; }

    public DateTime? BLDate { get; set; }

    public string BENo { get; set; }

    public DateTime? BEDate { get; set; }

    public string EFRNo { get; set; }

    public DateTime? EFRDate { get; set; }

    public string INVNo { get; set; }

    public DateTime? INVDate { get; set; }

    public string IPNo { get; set; }

    public DateTime? IPDate { get; set; }

    public decimal? FOBValueBDT { get; set; }

    public decimal? FOBValueUSD { get; set; }

    public string PaymentModeCode { get; set; }

    public DateTime? DocRecvDate { get; set; }

    public DateTime? ArrivalDate { get; set; }

    public DateTime? DeliveryDate { get; set; }

    public string Terms { get; set; }

    public string IsEnclosures { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }

    public decimal? MinimumAgencyCommission { get; set; }

    public decimal? OnInvoiceValue { get; set; }

    public int? NumberOfTransport { get; set; }

    public string PrifixId { get; set; }

    public string UndertakingNo { get; set; }

    public string ROTNo { get; set; }

    public string Remarks { get; set; }

    public int? NumberOfDemerageDay { get; set; }

    public string ContainerNo { get; set; }

    public decimal? Quantity { get; set; }

    public string QUnitTypeID { get; set; }

    public decimal? DocWeight { get; set; }

    public string WUnitTypeID { get; set; }

    public decimal? LCValue { get; set; }

    public string LCurrencyID { get; set; }

    public string Destination { get; set; }

    public string IsCollectBill { get; set; }

    public decimal? BillAmount { get; set; }

    public decimal? SpecialDiscount { get; set; }

    public string InvoiceCurrencyID { get; set; }

    public decimal? InvoiceValue { get; set; }

    public decimal? AssessableRate { get; set; }

    public decimal? AssessableValue { get; set; }
}