// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CF_BillEntryDetails
{
    public decimal TC { get; set; }

    public string BillDetailsID { get; set; }

    public string BillNo { get; set; }

    public string ExpenseHeadID { get; set; }

    public decimal? EstimatedAmount { get; set; }

    public decimal? ActualAmount { get; set; }

    public decimal? DifferentAmount { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }

    public string BillHead { get; set; }

    public decimal? ExpenseBillAmount { get; set; }
}