// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CF_DailyJobUpdateEntry
{
    public decimal TC { get; set; }

    public string DailyJobUpdateEntryID { get; set; }

    public string UpdateStatus { get; set; }

    public string UpdateRemarks { get; set; }

    public DateTime? UpdateDateTime { get; set; }

    public string JobNo { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }
}