// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CF_Def_PlaceOfLoading
{
    public int AutoID { get; set; }

    public string PlaceOfLoadingID { get; set; }

    public string PlaceOfLoadingName { get; set; }

    public string ShortName { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }
}