// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CF_Def_ExpenseType
{
    public int TC { get; set; }

    public string ExpenseTypeID { get; set; }

    public string ExpenseType { get; set; }

    public string ShortName { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string ExpenseLedgerCodeNo { get; set; }

    public string RevenueLedgerCodeNo { get; set; }

    public string AdvanceLedgerCode { get; set; }
}