// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CF_Def_ExpenseHead
{
    public int TC { get; set; }

    public string ExpenseHeadID { get; set; }

    public string ExpenseHead { get; set; }

    public string ShortName { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string SerialNo { get; set; }

    public string ExpenseTypeID { get; set; }

    public string IsReceiptable { get; set; }

    public decimal? Amount { get; set; }

    public string ServiceTypeID { get; set; }

    public string EntryType { get; set; }
}