// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CF_OperationalFundRequisitionEntry
{
    public decimal TC { get; set; }

    public string OFRNo { get; set; }

    public string PrifixId { get; set; }

    public DateTime? OFRDate { get; set; }

    public string JobNo { get; set; }

    public string ApprovedUser { get; set; }

    public DateTime? ApprovedDate { get; set; }

    public DateTime? ApprovedModifyDate { get; set; }

    public string BillAdjustApprovalUser { get; set; }

    public DateTime? BillAdjustApproveDate { get; set; }

    public DateTime? BillAdjustApproveModifyDate { get; set; }

    public decimal? PortCharge { get; set; }

    public decimal? AsycodaCharge { get; set; }

    public decimal? DutyByChallanCharge { get; set; }

    public decimal? ShippingCharge { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }

    public string CashBank { get; set; }

    public string BankAccount { get; set; }

    public string CashBank2 { get; set; }

    public string BankAccount2 { get; set; }

    public string ExpenseTypeID { get; set; }
}