// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Core_BankAccountInformation
{
    public decimal AutoID { get; set; }

    public string AccInfoID { get; set; }

    public string AccountName { get; set; }

    public string AccountNO { get; set; }

    public string BankID { get; set; }

    public string BranchID { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string UserInfoEmployeeID { get; set; }

    public string CompanyCode { get; set; }
}