// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Core_Company
{
    public string CompanyCode { get; set; }

    public string CompanyName { get; set; }

    public string CompanyShortName { get; set; }

    public string ImgTitle { get; set; }

    public string Address1 { get; set; }

    public string Address2 { get; set; }

    public string ZipCode { get; set; }

    public string City { get; set; }

    public string State { get; set; }

    public string Country { get; set; }

    public string Phone1 { get; set; }

    public string Phone2 { get; set; }

    public string Fax { get; set; }

    public string HotLine { get; set; }

    public string Email { get; set; }

    public string URL { get; set; }

    public string RegNo { get; set; }

    public string TIN { get; set; }

    public string BackImage { get; set; }

    public string BaseCurrency { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyBanglaName { get; set; }

    public string AddressBangla { get; set; }

    public int AutoID { get; set; }

    public string BIN { get; set; }
}