// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Core_ImporterInformation
{
    public decimal TC { get; set; }

    public string ImporterID { get; set; }

    public string ImporterName { get; set; }

    public string ImporterAddress { get; set; }

    public string Phone { get; set; }

    public string Website { get; set; }

    public string Email { get; set; }

    public string ImporterCode { get; set; }

    public string CountryId { get; set; }

    public string City { get; set; }

    public string StateOrProvince { get; set; }

    public string ZipCode { get; set; }

    public string VatRegNo { get; set; }

    public string Fax { get; set; }

    public string Remarks { get; set; }

    public string ContactPerson1 { get; set; }

    public string Designation1 { get; set; }

    public string Phone1 { get; set; }

    public string Email1 { get; set; }

    public string ContactPerson2 { get; set; }

    public string Designation2 { get; set; }

    public string Phone2 { get; set; }

    public string Email2 { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }
}