// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Core_Country
{
    public int CountryCode { get; set; }

    public string CountryID { get; set; }

    public string CountryName { get; set; }

    public string IOCCode { get; set; }

    public string ISOCode { get; set; }

    public DateTime? LDate { get; set; }

    public string LUser { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }
}