// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Core_Branch
{
    public decimal autoId { get; set; }

    public string BranchCode { get; set; }

    public string CompanyCode { get; set; }

    public string BranchName { get; set; }

    public string Address { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string Email { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string BanglaBranch { get; set; }

    public string AddressBangla { get; set; }
}