// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Country
{
    public int CountryID { get; set; }

    public string CountryCode { get; set; }

    public string CountryName { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<EmployeeTranningInfo> EmployeeTranningInfo { get; set; } = new List<EmployeeTranningInfo>();

    public virtual ICollection<Employees> EmployeesCountry { get; set; } = new List<Employees>();

    public virtual ICollection<Employees> EmployeesNationality { get; set; } = new List<Employees>();

    public virtual ICollection<Organization> Organization { get; set; } = new List<Organization>();

    public virtual ICollection<OrganizationBranches> OrganizationBranches { get; set; } = new List<OrganizationBranches>();

    public virtual Employees UpdatedByNavigation { get; set; }
}