// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Currencies
{
    public int CurrencyID { get; set; }

    public string CurrencyCode { get; set; }

    public string CurrencyName { get; set; }

    public string Symbol { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<EmployeeSalarySettings> EmployeeSalarySettings { get; set; } = new List<EmployeeSalarySettings>();

    public virtual ICollection<Localizations> Localizations { get; set; } = new List<Localizations>();

    public virtual Employees UpdatedByNavigation { get; set; }
}