// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CustomerHandilingCharge
{
    public decimal TC { get; set; }

    public string CHCID { get; set; }

    public string CHCHead { get; set; }

    public string CHCHeadDescription { get; set; }

    public string ShortName { get; set; }

    public string SerialNo { get; set; }

    public string IsReceiptable { get; set; }

    public string ExpenseTypeID { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }
}