// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class CustomerWiseCostingEntry
{
    public decimal TC { get; set; }

    public string CostingID { get; set; }

    public string CustomerID { get; set; }

    public decimal MinimumAgencyCommission { get; set; }

    public decimal OnInvoiceValue { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }

    public string ExpenseTypeID { get; set; }
}