// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Elements
{
    public int Id { get; set; }

    public int PageId { get; set; }

    public string Key { get; set; }

    public string Name { get; set; }

    public virtual Pages Page { get; set; }
}