// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeOfficeInfo
{
    public int EmployeeOfficeInfoID { get; set; }

    public int? EmployeeID { get; set; }

    public string EmployeeOfficeId { get; set; }

    public int? OrganizationID { get; set; }

    public int? OrganizationBranchID { get; set; }

    public int? DepartmentID { get; set; }

    public int? DesignationID { get; set; }

    public int? EmployeeTypeID { get; set; }

    public int? EmploymentNatureID { get; set; }

    public int? SeniorSupervisorId { get; set; }

    public int? ImmediateSupervisorId { get; set; }

    public int? HeadOfDepartmentId { get; set; }

    public string OfficePhone { get; set; }

    public string OfficeEmail { get; set; }

    public string AttendanceId { get; set; }

    public int? EmploymentStatusId { get; set; }

    public string AppointmentLetterNo { get; set; }

    public DateOnly? AppointmentLetterIssueDate { get; set; }

    public DateOnly? JoiningDate { get; set; }

    public DateOnly? ProvisionPeriodStartDate { get; set; }

    public int? ProvisionPeriod { get; set; }

    public int? ProvisionPeriodTtimeTypeID { get; set; }

    public DateOnly? ConfirmationDate { get; set; }

    public string ConfirmationLetterNo { get; set; }

    public DateOnly? ContractEndDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public decimal? DivisionID { get; set; }

    public decimal? EmploymentGradeID { get; set; }

    public decimal? EmploymentShiftID { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Departments Department { get; set; }

    public virtual Designations Designation { get; set; }

    public virtual HRM_Def_Division Division { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual EmployeeType EmployeeType { get; set; }

    public virtual HRM_Def_Grade EmploymentGrade { get; set; }

    public virtual EmploymentNature EmploymentNature { get; set; }

    public virtual HRM_ATD_Shift EmploymentShift { get; set; }

    public virtual Statuses EmploymentStatus { get; set; }

    public virtual Employees HeadOfDepartment { get; set; }

    public virtual Employees ImmediateSupervisor { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual OrganizationBranches OrganizationBranch { get; set; }

    public virtual ProvisionPeriodTtimeTypes ProvisionPeriodTtimeType { get; set; }

    public virtual Employees SeniorSupervisor { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}