// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeTranningInfo
{
    public int EmployeeTranningInfoID { get; set; }

    public int? EmployeeID { get; set; }

    public string TranningTitle { get; set; }

    public int? CountryID { get; set; }

    public string TopicCovered { get; set; }

    public int? TrainingYearID { get; set; }

    public string InstituteName { get; set; }

    public string YearDuration { get; set; }

    public string LocationName { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Country Country { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual TrainingYears TrainingYear { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}