// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeSalarySettings
{
    public int EmployeeSalarySettingsID { get; set; }

    public int? EmployeeID { get; set; }

    public string BankName { get; set; }

    public string BranchName { get; set; }

    public string AccountName { get; set; }

    public string AccountNo { get; set; }

    public string Address { get; set; }

    public string ATMCardNo { get; set; }

    public string RoutingNo { get; set; }

    public string SWIFTCode { get; set; }

    public string IFSCCode { get; set; }

    public string bKashAccountNo { get; set; }

    public string RoketAccountNo { get; set; }

    public string NagodAccountNo { get; set; }

    public string EmployeeGID { get; set; }

    public int? GradeID { get; set; }

    public decimal? Salary { get; set; }

    public int? CurrencyID { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int? PaymenPeriodTypeID { get; set; }

    public bool IsBenefitsEnabled { get; set; }

    public bool IsAllowanceEnabled { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Currencies Currency { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual Grade Grade { get; set; }

    public virtual PaymentPeriodTypes PaymenPeriodType { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}