// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeEducationalInfo
{
    public int EmployeeEducationalInfoID { get; set; }

    public int? EmployeeID { get; set; }

    public int? EducationLevelID { get; set; }

    public int? DegreeID { get; set; }

    public string MajorSubject { get; set; }

    public int? EducationBoardID { get; set; }

    public string InstitutionName { get; set; }

    public int? ResultTypeID { get; set; }

    public int? PassingYearID { get; set; }

    public string YearDuration { get; set; }

    public string Achievement { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Degree Degree { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual EducationBoard EducationBoard { get; set; }

    public virtual EducationLevels EducationLevel { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual PassingYears PassingYear { get; set; }

    public virtual ResultTypes ResultType { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}