// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeBaseAllowances
{
    public int EmployeeBaseAllowanceID { get; set; }

    public int? EmployeeID { get; set; }

    public decimal? ShiftAllowance { get; set; }

    public bool IsShiftAllowanceEnabled { get; set; }

    public decimal? HouseRentAllowancePercentage { get; set; }

    public bool IsHouseRentAllowancePercentageEnabled { get; set; }

    public decimal? MedicalAllowancePercentage { get; set; }

    public bool IsMedicalAllowancePercentageEnabled { get; set; }

    public decimal? ConveyanceAllowancePercentage { get; set; }

    public bool IsConveyanceAllowancePercentageEnabled { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public decimal? MobileAllowance { get; set; }

    public decimal? InternetAllowance { get; set; }

    public bool IsMobileAllowanceEnabled { get; set; }

    public bool IsInternetAllowanceEnabled { get; set; }

    public DateTime? MobileAllowanceEffectiveFrom { get; set; }

    public DateTime? InternetAllowanceEffectiveFrom { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}