// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeBaseBenefits
{
    public int EmployeeBaseBenefitID { get; set; }

    public int? EmployeeID { get; set; }

    public decimal? HealthInsurance { get; set; }

    public bool IsHealthInsuranceEnabled { get; set; }

    public decimal? PerformanceBonus { get; set; }

    public bool IsPerformanceBonusEnabled { get; set; }

    public int? YearlyEndBonusTypeID { get; set; }

    public bool IsYearlyEndBonusTypeIDEnabled { get; set; }

    public decimal? FastivalBonusPercentage { get; set; }

    public bool IsFastivalBonusPercentageEnabled { get; set; }

    public decimal? ProvidantFundEmployeePercentage { get; set; }

    public decimal? ProvidantFundOrganizationPercentage { get; set; }

    public bool IsProvidantFundEnabled { get; set; }

    public int? ServiceYearID { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual ServiceYears ServiceYear { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }

    public virtual YearlyEndBonusTypes YearlyEndBonusType { get; set; }
}