// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Employees
{
    public int EmployeeID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string FatherName { get; set; }

    public string MotherName { get; set; }

    public string MobileNumber { get; set; }

    public string Email { get; set; }

    public string BirthCertificateNo { get; set; }

    public string TIN { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public string AboutEmployee { get; set; }

    public string NID { get; set; }

    public string State { get; set; }

    public string City { get; set; }

    public string HouseNo { get; set; }

    public string RoadNo { get; set; }

    public string PostalCode { get; set; }

    public string EmployeeImageFileName { get; set; }

    public string EmployeeSignatureFileName { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public bool? HasUser { get; set; }

    public int? MaritalStatusID { get; set; }

    public int? GenderID { get; set; }

    public int? BloodGroupID { get; set; }

    public int? NationalityID { get; set; }

    public int? ReligionID { get; set; }

    public int? CountryID { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public string EmployeeCode { get; set; }

    public bool? IsActive { get; set; }

    public string CardNo { get; set; }

    public virtual ICollection<ActionLogs> ActionLogs { get; set; } = new List<ActionLogs>();

    public virtual ICollection<AlertForEmployee> AlertForEmployeeCreatedByNavigation { get; set; } = new List<AlertForEmployee>();

    public virtual ICollection<AlertForEmployee> AlertForEmployeeDeletedByNavigation { get; set; } = new List<AlertForEmployee>();

    public virtual ICollection<AlertForEmployee> AlertForEmployeeEmployee { get; set; } = new List<AlertForEmployee>();

    public virtual ICollection<AlertForEmployee> AlertForEmployeeUpdatedByNavigation { get; set; } = new List<AlertForEmployee>();

    public virtual ICollection<Alerts> AlertsCreatedByNavigation { get; set; } = new List<Alerts>();

    public virtual ICollection<Alerts> AlertsDeletedByNavigation { get; set; } = new List<Alerts>();

    public virtual ICollection<Alerts> AlertsUpdatedByNavigation { get; set; } = new List<Alerts>();

    public virtual ICollection<ApprovalLevelAssignments> ApprovalLevelAssignmentsApproverEmployee { get; set; } = new List<ApprovalLevelAssignments>();

    public virtual ICollection<ApprovalLevelAssignments> ApprovalLevelAssignmentsCreatedByNavigation { get; set; } = new List<ApprovalLevelAssignments>();

    public virtual ICollection<ApprovalLevelAssignments> ApprovalLevelAssignmentsDeletedByNavigation { get; set; } = new List<ApprovalLevelAssignments>();

    public virtual ICollection<ApprovalLevelAssignments> ApprovalLevelAssignmentsUpdatedByNavigation { get; set; } = new List<ApprovalLevelAssignments>();

    public virtual ICollection<ApprovalSettings> ApprovalSettingsCreatedByNavigation { get; set; } = new List<ApprovalSettings>();

    public virtual ICollection<ApprovalSettings> ApprovalSettingsDeletedByNavigation { get; set; } = new List<ApprovalSettings>();

    public virtual ICollection<ApprovalSettings> ApprovalSettingsSelfExceptionApproval { get; set; } = new List<ApprovalSettings>();

    public virtual ICollection<ApprovalSettings> ApprovalSettingsUpdatedByNavigation { get; set; } = new List<ApprovalSettings>();

    public virtual ICollection<ApprovalTypes> ApprovalTypesCreatedByNavigation { get; set; } = new List<ApprovalTypes>();

    public virtual ICollection<ApprovalTypes> ApprovalTypesDeletedByNavigation { get; set; } = new List<ApprovalTypes>();

    public virtual ICollection<ApprovalTypes> ApprovalTypesUpdatedByNavigation { get; set; } = new List<ApprovalTypes>();

    public virtual ICollection<ApplicationUser> AspNetUsers { get; set; } = new List<ApplicationUser>();

    public virtual BloodGroup BloodGroup { get; set; }

    public virtual ICollection<BloodGroup> BloodGroupCreatedByNavigation { get; set; } = new List<BloodGroup>();

    public virtual ICollection<BloodGroup> BloodGroupDeletedByNavigation { get; set; } = new List<BloodGroup>();

    public virtual ICollection<BloodGroup> BloodGroupUpdatedByNavigation { get; set; } = new List<BloodGroup>();

    public virtual Country Country { get; set; }

    public virtual ICollection<Country> CountryCreatedByNavigation { get; set; } = new List<Country>();

    public virtual ICollection<Country> CountryDeletedByNavigation { get; set; } = new List<Country>();

    public virtual ICollection<Country> CountryUpdatedByNavigation { get; set; } = new List<Country>();

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual ICollection<Currencies> CurrenciesCreatedByNavigation { get; set; } = new List<Currencies>();

    public virtual ICollection<Currencies> CurrenciesDeletedByNavigation { get; set; } = new List<Currencies>();

    public virtual ICollection<Currencies> CurrenciesUpdatedByNavigation { get; set; } = new List<Currencies>();

    public virtual ICollection<Degree> DegreeCreatedByNavigation { get; set; } = new List<Degree>();

    public virtual ICollection<Degree> DegreeDeletedByNavigation { get; set; } = new List<Degree>();

    public virtual ICollection<Degree> DegreeUpdatedByNavigation { get; set; } = new List<Degree>();

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<Departments> DepartmentsCreatedByNavigation { get; set; } = new List<Departments>();

    public virtual ICollection<Departments> DepartmentsDeletedByNavigation { get; set; } = new List<Departments>();

    public virtual ICollection<Departments> DepartmentsDepartmentHeadEmp { get; set; } = new List<Departments>();

    public virtual ICollection<Departments> DepartmentsUpdatedByNavigation { get; set; } = new List<Departments>();

    public virtual ICollection<Designations> DesignationsCreatedByNavigation { get; set; } = new List<Designations>();

    public virtual ICollection<Designations> DesignationsDeletedByNavigation { get; set; } = new List<Designations>();

    public virtual ICollection<Designations> DesignationsUpdatedByNavigation { get; set; } = new List<Designations>();

    public virtual ICollection<EducationBoard> EducationBoardDeletedByNavigation { get; set; } = new List<EducationBoard>();

    public virtual ICollection<EducationBoard> EducationBoardUpdatedByNavigation { get; set; } = new List<EducationBoard>();

    public virtual ICollection<EducationLevels> EducationLevelsCreatedByNavigation { get; set; } = new List<EducationLevels>();

    public virtual ICollection<EducationLevels> EducationLevelsDeletedByNavigation { get; set; } = new List<EducationLevels>();

    public virtual ICollection<EducationLevels> EducationLevelsUpdatedByNavigation { get; set; } = new List<EducationLevels>();

    public virtual ICollection<EmailSettings> EmailSettingsCreatedByNavigation { get; set; } = new List<EmailSettings>();

    public virtual ICollection<EmailSettings> EmailSettingsDeletedByNavigation { get; set; } = new List<EmailSettings>();

    public virtual ICollection<EmailSettings> EmailSettingsUpdatedByNavigation { get; set; } = new List<EmailSettings>();

    public virtual ICollection<EmployeeActionTypes> EmployeeActionTypesCreatedByNavigation { get; set; } = new List<EmployeeActionTypes>();

    public virtual ICollection<EmployeeActionTypes> EmployeeActionTypesDeletedByNavigation { get; set; } = new List<EmployeeActionTypes>();

    public virtual ICollection<EmployeeActionTypes> EmployeeActionTypesUpdatedByNavigation { get; set; } = new List<EmployeeActionTypes>();

    public virtual ICollection<EmployeeAdditionalInfo> EmployeeAdditionalInfoCreatedByNavigation { get; set; } = new List<EmployeeAdditionalInfo>();

    public virtual ICollection<EmployeeAdditionalInfo> EmployeeAdditionalInfoDeletedByNavigation { get; set; } = new List<EmployeeAdditionalInfo>();

    public virtual ICollection<EmployeeAdditionalInfo> EmployeeAdditionalInfoEmployee { get; set; } = new List<EmployeeAdditionalInfo>();

    public virtual ICollection<EmployeeAdditionalInfo> EmployeeAdditionalInfoUpdatedByNavigation { get; set; } = new List<EmployeeAdditionalInfo>();

    public virtual ICollection<EmployeeBaseAllowances> EmployeeBaseAllowancesCreatedByNavigation { get; set; } = new List<EmployeeBaseAllowances>();

    public virtual ICollection<EmployeeBaseAllowances> EmployeeBaseAllowancesDeletedByNavigation { get; set; } = new List<EmployeeBaseAllowances>();

    public virtual ICollection<EmployeeBaseAllowances> EmployeeBaseAllowancesEmployee { get; set; } = new List<EmployeeBaseAllowances>();

    public virtual ICollection<EmployeeBaseAllowances> EmployeeBaseAllowancesUpdatedByNavigation { get; set; } = new List<EmployeeBaseAllowances>();

    public virtual ICollection<EmployeeBaseBenefits> EmployeeBaseBenefitsCreatedByNavigation { get; set; } = new List<EmployeeBaseBenefits>();

    public virtual ICollection<EmployeeBaseBenefits> EmployeeBaseBenefitsDeletedByNavigation { get; set; } = new List<EmployeeBaseBenefits>();

    public virtual ICollection<EmployeeBaseBenefits> EmployeeBaseBenefitsEmployee { get; set; } = new List<EmployeeBaseBenefits>();

    public virtual ICollection<EmployeeBaseBenefits> EmployeeBaseBenefitsUpdatedByNavigation { get; set; } = new List<EmployeeBaseBenefits>();

    public virtual ICollection<EmployeeBasePaymentModes> EmployeeBasePaymentModesCreatedByNavigation { get; set; } = new List<EmployeeBasePaymentModes>();

    public virtual ICollection<EmployeeBasePaymentModes> EmployeeBasePaymentModesDeletedByNavigation { get; set; } = new List<EmployeeBasePaymentModes>();

    public virtual ICollection<EmployeeBasePaymentModes> EmployeeBasePaymentModesEmployee { get; set; } = new List<EmployeeBasePaymentModes>();

    public virtual ICollection<EmployeeBasePaymentModes> EmployeeBasePaymentModesUpdatedByNavigation { get; set; } = new List<EmployeeBasePaymentModes>();

    public virtual ICollection<EmployeeEducationalInfo> EmployeeEducationalInfoCreatedByNavigation { get; set; } = new List<EmployeeEducationalInfo>();

    public virtual ICollection<EmployeeEducationalInfo> EmployeeEducationalInfoDeletedByNavigation { get; set; } = new List<EmployeeEducationalInfo>();

    public virtual ICollection<EmployeeEducationalInfo> EmployeeEducationalInfoEmployee { get; set; } = new List<EmployeeEducationalInfo>();

    public virtual ICollection<EmployeeEducationalInfo> EmployeeEducationalInfoUpdatedByNavigation { get; set; } = new List<EmployeeEducationalInfo>();

    public virtual ICollection<EmployeeEmeContacts> EmployeeEmeContactsCreatedByNavigation { get; set; } = new List<EmployeeEmeContacts>();

    public virtual ICollection<EmployeeEmeContacts> EmployeeEmeContactsDeletedByNavigation { get; set; } = new List<EmployeeEmeContacts>();

    public virtual ICollection<EmployeeEmeContacts> EmployeeEmeContactsEmployee { get; set; } = new List<EmployeeEmeContacts>();

    public virtual ICollection<EmployeeEmeContacts> EmployeeEmeContactsUpdatedByNavigation { get; set; } = new List<EmployeeEmeContacts>();

    public virtual ICollection<EmployeeFamilyInfo> EmployeeFamilyInfoCreatedByNavigation { get; set; } = new List<EmployeeFamilyInfo>();

    public virtual ICollection<EmployeeFamilyInfo> EmployeeFamilyInfoDeletedByNavigation { get; set; } = new List<EmployeeFamilyInfo>();

    public virtual ICollection<EmployeeFamilyInfo> EmployeeFamilyInfoEmployee { get; set; } = new List<EmployeeFamilyInfo>();

    public virtual ICollection<EmployeeFamilyInfo> EmployeeFamilyInfoUpdatedByNavigation { get; set; } = new List<EmployeeFamilyInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoCreatedByNavigation { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoDeletedByNavigation { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoEmployee { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoHeadOfDepartment { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoImmediateSupervisor { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoSeniorSupervisor { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfoUpdatedByNavigation { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeSalarySettings> EmployeeSalarySettingsCreatedByNavigation { get; set; } = new List<EmployeeSalarySettings>();

    public virtual ICollection<EmployeeSalarySettings> EmployeeSalarySettingsDeletedByNavigation { get; set; } = new List<EmployeeSalarySettings>();

    public virtual ICollection<EmployeeSalarySettings> EmployeeSalarySettingsEmployee { get; set; } = new List<EmployeeSalarySettings>();

    public virtual ICollection<EmployeeSalarySettings> EmployeeSalarySettingsUpdatedByNavigation { get; set; } = new List<EmployeeSalarySettings>();

    public virtual ICollection<EmployeeTranningInfo> EmployeeTranningInfoCreatedByNavigation { get; set; } = new List<EmployeeTranningInfo>();

    public virtual ICollection<EmployeeTranningInfo> EmployeeTranningInfoDeletedByNavigation { get; set; } = new List<EmployeeTranningInfo>();

    public virtual ICollection<EmployeeTranningInfo> EmployeeTranningInfoEmployee { get; set; } = new List<EmployeeTranningInfo>();

    public virtual ICollection<EmployeeTranningInfo> EmployeeTranningInfoUpdatedByNavigation { get; set; } = new List<EmployeeTranningInfo>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferApprovalPerson { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferCreatedByNavigation { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferDeletedByNavigation { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferEmployee { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryApprovalPerson { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryCreatedByNavigation { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryDeletedByNavigation { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryUpdatedByNavigation { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferUpdatedByNavigation { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeType> EmployeeTypeCreatedByNavigation { get; set; } = new List<EmployeeType>();

    public virtual ICollection<EmployeeType> EmployeeTypeDeletedByNavigation { get; set; } = new List<EmployeeType>();

    public virtual ICollection<EmployeeType> EmployeeTypeUpdatedByNavigation { get; set; } = new List<EmployeeType>();

    public virtual ICollection<EmploymentNature> EmploymentNatureCreatedByNavigation { get; set; } = new List<EmploymentNature>();

    public virtual ICollection<EmploymentNature> EmploymentNatureDeletedByNavigation { get; set; } = new List<EmploymentNature>();

    public virtual ICollection<EmploymentNature> EmploymentNatureUpdatedByNavigation { get; set; } = new List<EmploymentNature>();

    public virtual Genders Gender { get; set; }

    public virtual ICollection<Genders> GendersCreatedByNavigation { get; set; } = new List<Genders>();

    public virtual ICollection<Genders> GendersDeletedByNavigation { get; set; } = new List<Genders>();

    public virtual ICollection<Genders> GendersUpdatedByNavigation { get; set; } = new List<Genders>();

    public virtual ICollection<Grade> GradeCreatedByNavigation { get; set; } = new List<Grade>();

    public virtual ICollection<Grade> GradeDeletedByNavigation { get; set; } = new List<Grade>();

    public virtual ICollection<Grade> GradeUpdatedByNavigation { get; set; } = new List<Grade>();

    public virtual ICollection<Holidays> HolidaysCreatedByNavigation { get; set; } = new List<Holidays>();

    public virtual ICollection<Holidays> HolidaysDeletedByNavigation { get; set; } = new List<Holidays>();

    public virtual ICollection<Holidays> HolidaysUpdatedByNavigation { get; set; } = new List<Holidays>();

    public virtual ICollection<Employees> InverseCreatedByNavigation { get; set; } = new List<Employees>();

    public virtual ICollection<Employees> InverseDeletedByNavigation { get; set; } = new List<Employees>();

    public virtual ICollection<Employees> InverseUpdatedByNavigation { get; set; } = new List<Employees>();

    public virtual ICollection<LicenceTypes> LicenceTypesCreatedByNavigation { get; set; } = new List<LicenceTypes>();

    public virtual ICollection<LicenceTypes> LicenceTypesDeletedByNavigation { get; set; } = new List<LicenceTypes>();

    public virtual ICollection<LicenceTypes> LicenceTypesUpdatedByNavigation { get; set; } = new List<LicenceTypes>();

    public virtual ICollection<Localizations> LocalizationsCreatedByNavigation { get; set; } = new List<Localizations>();

    public virtual ICollection<Localizations> LocalizationsDeletedByNavigation { get; set; } = new List<Localizations>();

    public virtual ICollection<Localizations> LocalizationsUpdatedByNavigation { get; set; } = new List<Localizations>();

    public virtual MaritalStatus MaritalStatus { get; set; }

    public virtual ICollection<MaritalStatus> MaritalStatusCreatedByNavigation { get; set; } = new List<MaritalStatus>();

    public virtual ICollection<MaritalStatus> MaritalStatusUpdatedByNavigation { get; set; } = new List<MaritalStatus>();

    public virtual ICollection<MessageContent> MessageContentCreatedByNavigation { get; set; } = new List<MessageContent>();

    public virtual ICollection<MessageContent> MessageContentDeletedByNavigation { get; set; } = new List<MessageContent>();

    public virtual ICollection<MessageContent> MessageContentUpdatedByNavigation { get; set; } = new List<MessageContent>();

    public virtual Country Nationality { get; set; }

    public virtual ICollection<OTPSettings> OTPSettingsCreatedByNavigation { get; set; } = new List<OTPSettings>();

    public virtual ICollection<OTPSettings> OTPSettingsDeletedByNavigation { get; set; } = new List<OTPSettings>();

    public virtual ICollection<OTPSettings> OTPSettingsUpdatedByNavigation { get; set; } = new List<OTPSettings>();

    public virtual ICollection<OrganizationBranches> OrganizationBranchesCreatedByNavigation { get; set; } = new List<OrganizationBranches>();

    public virtual ICollection<OrganizationBranches> OrganizationBranchesDeletedByNavigation { get; set; } = new List<OrganizationBranches>();

    public virtual ICollection<OrganizationBranches> OrganizationBranchesUpdatedByNavigation { get; set; } = new List<OrganizationBranches>();

    public virtual ICollection<Organization> OrganizationCreatedByNavigation { get; set; } = new List<Organization>();

    public virtual ICollection<Organization> OrganizationDeletedByNavigation { get; set; } = new List<Organization>();

    public virtual ICollection<Organization> OrganizationUpdatedByNavigation { get; set; } = new List<Organization>();

    public virtual ICollection<PassingYears> PassingYearsCreatedByNavigation { get; set; } = new List<PassingYears>();

    public virtual ICollection<PassingYears> PassingYearsDeletedByNavigation { get; set; } = new List<PassingYears>();

    public virtual ICollection<PassingYears> PassingYearsUpdatedByNavigation { get; set; } = new List<PassingYears>();

    public virtual ICollection<PaymentModes> PaymentModesCreatedByNavigation { get; set; } = new List<PaymentModes>();

    public virtual ICollection<PaymentModes> PaymentModesDeletedByNavigation { get; set; } = new List<PaymentModes>();

    public virtual ICollection<PaymentModes> PaymentModesUpdatedByNavigation { get; set; } = new List<PaymentModes>();

    public virtual ICollection<PaymentPeriodTypes> PaymentPeriodTypesCreatedByNavigation { get; set; } = new List<PaymentPeriodTypes>();

    public virtual ICollection<PaymentPeriodTypes> PaymentPeriodTypesDeletedByNavigation { get; set; } = new List<PaymentPeriodTypes>();

    public virtual ICollection<PaymentPeriodTypes> PaymentPeriodTypesUpdatedByNavigation { get; set; } = new List<PaymentPeriodTypes>();

    public virtual ICollection<Percentages> PercentagesCreatedByNavigation { get; set; } = new List<Percentages>();

    public virtual ICollection<Percentages> PercentagesDeletedByNavigation { get; set; } = new List<Percentages>();

    public virtual ICollection<Percentages> PercentagesUpdatedByNavigation { get; set; } = new List<Percentages>();

    public virtual ICollection<ProbetionPeriodSettings> ProbetionPeriodSettingsCreatedByNavigation { get; set; } = new List<ProbetionPeriodSettings>();

    public virtual ICollection<ProbetionPeriodSettings> ProbetionPeriodSettingsDeletedByNavigation { get; set; } = new List<ProbetionPeriodSettings>();

    public virtual ICollection<ProbetionPeriodSettings> ProbetionPeriodSettingsUpdatedByNavigation { get; set; } = new List<ProbetionPeriodSettings>();

    public virtual ICollection<ProvisionPeriodTtimeTypes> ProvisionPeriodTtimeTypesCreatedByNavigation { get; set; } = new List<ProvisionPeriodTtimeTypes>();

    public virtual ICollection<ProvisionPeriodTtimeTypes> ProvisionPeriodTtimeTypesDeletedByNavigation { get; set; } = new List<ProvisionPeriodTtimeTypes>();

    public virtual ICollection<ProvisionPeriodTtimeTypes> ProvisionPeriodTtimeTypesUpdatedByNavigation { get; set; } = new List<ProvisionPeriodTtimeTypes>();

    public virtual Religions Religion { get; set; }

    public virtual ICollection<Religions> ReligionsCreatedByNavigation { get; set; } = new List<Religions>();

    public virtual ICollection<Religions> ReligionsDeletedByNavigation { get; set; } = new List<Religions>();

    public virtual ICollection<Religions> ReligionsUpdatedByNavigation { get; set; } = new List<Religions>();

    public virtual ICollection<ReportContent> ReportContentCreatedByNavigation { get; set; } = new List<ReportContent>();

    public virtual ICollection<ReportContent> ReportContentDeletedByNavigation { get; set; } = new List<ReportContent>();

    public virtual ICollection<ReportContent> ReportContentUpdatedByNavigation { get; set; } = new List<ReportContent>();

    public virtual ICollection<ResultTypes> ResultTypesCreatedByNavigation { get; set; } = new List<ResultTypes>();

    public virtual ICollection<ResultTypes> ResultTypesDeletedByNavigation { get; set; } = new List<ResultTypes>();

    public virtual ICollection<ResultTypes> ResultTypesUpdatedByNavigation { get; set; } = new List<ResultTypes>();

    public virtual ICollection<SMSSettings> SMSSettingsCreatedByNavigation { get; set; } = new List<SMSSettings>();

    public virtual ICollection<SMSSettings> SMSSettingsDeletedByNavigation { get; set; } = new List<SMSSettings>();

    public virtual ICollection<SMSSettings> SMSSettingsUpdatedByNavigation { get; set; } = new List<SMSSettings>();

    public virtual ICollection<ServiceYears> ServiceYearsCreatedByNavigation { get; set; } = new List<ServiceYears>();

    public virtual ICollection<ServiceYears> ServiceYearsDeletedByNavigation { get; set; } = new List<ServiceYears>();

    public virtual ICollection<ServiceYears> ServiceYearsUpdatedByNavigation { get; set; } = new List<ServiceYears>();

    public virtual ICollection<Statuses> StatusesCreatedByNavigation { get; set; } = new List<Statuses>();

    public virtual ICollection<Statuses> StatusesDeletedByNavigation { get; set; } = new List<Statuses>();

    public virtual ICollection<Statuses> StatusesUpdatedByNavigation { get; set; } = new List<Statuses>();

    public virtual ICollection<TrainingYears> TrainingYearsCreatedByNavigation { get; set; } = new List<TrainingYears>();

    public virtual ICollection<TrainingYears> TrainingYearsDeletedByNavigation { get; set; } = new List<TrainingYears>();

    public virtual ICollection<TrainingYears> TrainingYearsUpdatedByNavigation { get; set; } = new List<TrainingYears>();

    public virtual ICollection<UnitTypes> UnitTypesCreatedByNavigation { get; set; } = new List<UnitTypes>();

    public virtual ICollection<UnitTypes> UnitTypesDeletedByNavigation { get; set; } = new List<UnitTypes>();

    public virtual ICollection<UnitTypes> UnitTypesUpdatedByNavigation { get; set; } = new List<UnitTypes>();

    public virtual Employees UpdatedByNavigation { get; set; }

    public virtual ICollection<YearlyEndBonusTypes> YearlyEndBonusTypesCreatedByNavigation { get; set; } = new List<YearlyEndBonusTypes>();

    public virtual ICollection<YearlyEndBonusTypes> YearlyEndBonusTypesDeletedByNavigation { get; set; } = new List<YearlyEndBonusTypes>();

    public virtual ICollection<YearlyEndBonusTypes> YearlyEndBonusTypesUpdatedByNavigation { get; set; } = new List<YearlyEndBonusTypes>();
}