// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class EmployeeAdditionalInfo
{
    public int EmployeeAdditionalInfoID { get; set; }

    public int? EmployeeID { get; set; }

    public string PasportName { get; set; }

    public string PasportNo { get; set; }

    public string PasportPlaceOfIssue { get; set; }

    public DateTime? PasportIssueDate { get; set; }

    public DateTime? PasportExpireDate { get; set; }

    public string DrivingLicenceNo { get; set; }

    public int? LicenceTypeID { get; set; }

    public DateTime? DrivingLicenceIssueDate { get; set; }

    public DateTime? DrivingLicenceExpireDate { get; set; }

    public string SymbolOfVehicleClass { get; set; }

    public string DrivingLicencePlaceOfIssue { get; set; }

    public string WorkPermaitNumber { get; set; }

    public string WorkPermitType { get; set; }

    public DateTime? WorkPermitEffectiveDate { get; set; }

    public DateTime? WorkPermitExpireDate { get; set; }

    public DateTime? VisaExpireDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual Employees Employee { get; set; }

    public virtual LicenceTypes LicenceType { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}