// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class GetExpenseHeadReportResult
    {
        [StringLength(300)]
        public string CompanyName { get; set; }
        [StringLength(2147483647)]
        public string Address1 { get; set; }
        [StringLength(50)]
        public string ExpenseHeadID { get; set; }
        [StringLength(50)]
        public string ExpenseHead { get; set; }
        [StringLength(50)]
        public string ShortName { get; set; }
        [StringLength(50)]
        public string SerialNo { get; set; }
        [StringLength(50)]
        public string IsReceiptable { get; set; }
        [StringLength(50)]
        public string ServiceProvidedBy { get; set; }
        [StringLength(100)]
        public string ExpenseType { get; set; }
    }
}
