// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class HRM_ATD_CompanyWeekEnd
{
    public decimal autoId { get; set; }

    public string CompanyWeekEndCode { get; set; }

    public string Weekend { get; set; }

    public DateTime EffectiveDate { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }
}