// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class HRM_Def_Designation
{
    public decimal autoId { get; set; }

    public string DesignationCode { get; set; }

    public string DesignationName { get; set; }

    public string DesignationShortName { get; set; }

    public string GradeCode { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string StepNoId { get; set; }

    public string BanglaDesignation { get; set; }

    public string BanglaShortName { get; set; }
}