// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class HRM_ATD_Shift
{
    public decimal autoId { get; set; }

    public string ShiftCode { get; set; }

    public string ShiftName { get; set; }

    public string ShiftShortName { get; set; }

    public DateTime ShiftStartTime { get; set; }

    public DateTime ShiftEndTime { get; set; }

    public DateTime LateTime { get; set; }

    public DateTime AbsentTime { get; set; }

    public DateTime WEF { get; set; }

    public string Remarks { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string ShiftTypeID { get; set; }

    public DateTime LunchInTime { get; set; }

    public DateTime LunchOutTime { get; set; }

    public decimal LunchBreakHour { get; set; }

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfo { get; set; } = new List<EmployeeOfficeInfo>();
}