// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class HRM_Def_Grade
{
    public decimal autoId { get; set; }

    public string GradeCode { get; set; }

    public string GradeName { get; set; }

    public string GradeShortName { get; set; }

    public decimal? FromGrossSalary { get; set; }

    public decimal? ToGrossSalary { get; set; }

    public string GradeTypeID { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfo { get; set; } = new List<EmployeeOfficeInfo>();
}