// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class HRM_Def_Department
{
    public decimal autoId { get; set; }

    public string DepartmentCode { get; set; }

    public string DepartmentName { get; set; }

    public string DepartmentShortName { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string BanglaDepartment { get; set; }

    public string BanglaShortName { get; set; }

    public string CompanyCode { get; set; }
}