// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class InventoryTx
{
    public long TxID { get; set; }

    public long InventoryID { get; set; }

    public string TxType { get; set; }

    public decimal Quantity { get; set; }

    public DateTime? TxDate { get; set; }

    public string RefType { get; set; }

    public string RefID { get; set; }

    public string Note { get; set; }

    public virtual Inventory Inventory { get; set; }
}