// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Inventory
{
    public long InventoryID { get; set; }

    public int ProductID { get; set; }

    public int? VariantID { get; set; }

    public int WarehouseID { get; set; }

    public decimal QuantityOnHand { get; set; }

    public DateTime? LastUpdated { get; set; }

    public virtual ICollection<InventoryTx> InventoryTx { get; set; } = new List<InventoryTx>();

    public virtual Product Product { get; set; }

    public virtual ProductVariant Variant { get; set; }
}