// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class LanguageInd_hi
{
    public int Id { get; set; }

    public string EngText { get; set; }

    public string TranslatedText { get; set; }
}