// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class LanguageLists
{
    public int ID { get; set; }

    public string LanguageCode { get; set; }

    public string LanguageName { get; set; }

    public virtual ICollection<Localizations> Localizations { get; set; } = new List<Localizations>();
}