// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class LanguageMainTables
{
    public int ID { get; set; }

    public string TextCode { get; set; }

    public string EnglishText { get; set; }

    public bool IsModified { get; set; }
}