// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Localizations
{
    public int LocalizationID { get; set; }

    public int? OrganizationID { get; set; }

    public int? LanguageID { get; set; }

    public int? TimezoneID { get; set; }

    public int? DateFormatID { get; set; }

    public int? TimeFormatID { get; set; }

    public int? CurrencyID { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Currencies Currency { get; set; }

    public virtual DateFormats DateFormat { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual LanguageLists Language { get; set; }

    public virtual Organization Organization { get; set; }

    public virtual TimeFormats TimeFormat { get; set; }

    public virtual Timezones Timezone { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}