// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class MenuTab
{
    public int MenuTabId { get; set; }

    public string Title { get; set; }

    public string Type { get; set; }

    public int? ParentId { get; set; }

    public int OrderBy { get; set; }

    public string ControllerName { get; set; }

    public string ViewName { get; set; }

    public string Icon { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<MenuTab> InverseParent { get; set; } = new List<MenuTab>();

    public virtual MenuTab Parent { get; set; }

    public virtual ICollection<RoleModulePermissions> RoleModulePermissions { get; set; } = new List<RoleModulePermissions>();
}