// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Organization
{
    public int OrganizationID { get; set; }

    public string OrganizationName { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public int TenantInfoId { get; set; }

    public string EmailAddress { get; set; }

    public string Phone { get; set; }

    public string Fax { get; set; }

    public string WebAddress { get; set; }

    public string LogoLink { get; set; }

    public string FaviconLink { get; set; }

    public string Address { get; set; }

    public int? CountryID { get; set; }

    public string Street { get; set; }

    public string City { get; set; }

    public string PostCode { get; set; }

    public decimal? Latitude { get; set; }

    public decimal? Longitude { get; set; }

    public virtual ICollection<ApprovalSettings> ApprovalSettings { get; set; } = new List<ApprovalSettings>();

    public virtual ICollection<ApprovalTypes> ApprovalTypes { get; set; } = new List<ApprovalTypes>();

    public virtual ICollection<ApplicationRole> AspNetRoles { get; set; } = new List<ApplicationRole>();

    public virtual ICollection<ApplicationUser> AspNetUsers { get; set; } = new List<ApplicationUser>();

    public virtual Country Country { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<Departments> Departments { get; set; } = new List<Departments>();

    public virtual ICollection<Designations> Designations { get; set; } = new List<Designations>();

    public virtual ICollection<EmailSettings> EmailSettings { get; set; } = new List<EmailSettings>();

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfo { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferFromOrganization { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryFromOrganization { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistoryToOrganization { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransferToOrganization { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<Holidays> Holidays { get; set; } = new List<Holidays>();

    public virtual ICollection<Localizations> Localizations { get; set; } = new List<Localizations>();

    public virtual ICollection<OTPSettings> OTPSettings { get; set; } = new List<OTPSettings>();

    public virtual ICollection<OrganizationBranches> OrganizationBranches { get; set; } = new List<OrganizationBranches>();

    public virtual ICollection<ProbetionPeriodSettings> ProbetionPeriodSettings { get; set; } = new List<ProbetionPeriodSettings>();

    public virtual ICollection<SMSSettings> SMSSettings { get; set; } = new List<SMSSettings>();

    public virtual TenantInfo TenantInfo { get; set; }

    public virtual Employees UpdatedByNavigation { get; set; }
}