// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Pages
{
    public int Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Elements> Elements { get; set; } = new List<Elements>();

    public virtual ICollection<RoleElementPermissions> RoleElementPermissions { get; set; } = new List<RoleElementPermissions>();
}