// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ProductType
{
    public int ProductTypeID { get; set; }

    public string TypeName { get; set; }

    public virtual ICollection<Product> Product { get; set; } = new List<Product>();
}