// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ProductPrice
{
    public long PriceID { get; set; }

    public int ProductID { get; set; }

    public int? VariantID { get; set; }

    public decimal UnitPrice { get; set; }

    public string Currency { get; set; }

    public DateOnly EffectiveFrom { get; set; }

    public DateOnly? EffectiveTo { get; set; }

    public virtual Product Product { get; set; }

    public virtual ProductVariant Variant { get; set; }
}