// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class ProductVariant
{
    public int VariantID { get; set; }

    public int ProductID { get; set; }

    public string VariantCode { get; set; }

    public string VariantName { get; set; }

    public bool? IsDefault { get; set; }

    public bool? IsActive { get; set; }

    public virtual ICollection<BundleComponent> BundleComponent { get; set; } = new List<BundleComponent>();

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual Product Product { get; set; }

    public virtual ICollection<ProductPrice> ProductPrice { get; set; } = new List<ProductPrice>();

    public virtual ICollection<PromotionCondition> PromotionCondition { get; set; } = new List<PromotionCondition>();

    public virtual ICollection<PromotionProduct> PromotionProduct { get; set; } = new List<PromotionProduct>();

    public virtual ICollection<PromotionReward> PromotionReward { get; set; } = new List<PromotionReward>();

    public virtual ICollection<SalesLine> SalesLine { get; set; } = new List<SalesLine>();

    public virtual ICollection<VariantAttribute> VariantAttribute { get; set; } = new List<VariantAttribute>();
}