// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Product
{
    public int ProductID { get; set; }

    public string ProductCode { get; set; }

    public string ProductName { get; set; }

    public int ProductTypeID { get; set; }

    public int? CategoryID { get; set; }

    public int? BrandID { get; set; }

    public string BaseUOM { get; set; }

    public bool? IsActive { get; set; }

    public DateTime? CreatedOn { get; set; }

    public virtual ICollection<BundleComponent> BundleComponentBundleProduct { get; set; } = new List<BundleComponent>();

    public virtual ICollection<BundleComponent> BundleComponentComponentProd { get; set; } = new List<BundleComponent>();

    public virtual ICollection<Inventory> Inventory { get; set; } = new List<Inventory>();

    public virtual ICollection<ProductPrice> ProductPrice { get; set; } = new List<ProductPrice>();

    public virtual ProductType ProductType { get; set; }

    public virtual ICollection<ProductVariant> ProductVariant { get; set; } = new List<ProductVariant>();

    public virtual ICollection<PromotionCondition> PromotionCondition { get; set; } = new List<PromotionCondition>();

    public virtual ICollection<PromotionProduct> PromotionProduct { get; set; } = new List<PromotionProduct>();

    public virtual ICollection<PromotionReward> PromotionReward { get; set; } = new List<PromotionReward>();

    public virtual ICollection<SalesLine> SalesLine { get; set; } = new List<SalesLine>();
}