// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class PromoApplication
{
    public long ApplyID { get; set; }

    public long PromotionID { get; set; }

    public long InvoiceID { get; set; }

    public long? LineID { get; set; }

    public DateTime? AppliedOn { get; set; }

    public string Details { get; set; }

    public virtual SalesInvoice Invoice { get; set; }

    public virtual SalesLine Line { get; set; }

    public virtual Promotion Promotion { get; set; }
}