// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Promotion
{
    public long PromotionID { get; set; }

    public string PromoCode { get; set; }

    public string PromoName { get; set; }

    public string PromoType { get; set; }

    public string Description { get; set; }

    public DateOnly StartDate { get; set; }

    public DateOnly? EndDate { get; set; }

    public bool? IsActive { get; set; }

    public int? Priority { get; set; }

    public int? MaxApplications { get; set; }

    public string PromoScope { get; set; }

    public virtual ICollection<PromoApplication> PromoApplication { get; set; } = new List<PromoApplication>();

    public virtual ICollection<PromotionCondition> PromotionCondition { get; set; } = new List<PromotionCondition>();

    public virtual ICollection<PromotionProduct> PromotionProduct { get; set; } = new List<PromotionProduct>();

    public virtual ICollection<PromotionReward> PromotionReward { get; set; } = new List<PromotionReward>();
}