// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class PromotionProduct
{
    public long PromotionProductID { get; set; }

    public long PromotionID { get; set; }

    public int ProductID { get; set; }

    public int? VariantID { get; set; }

    public virtual Product Product { get; set; }

    public virtual Promotion Promotion { get; set; }

    public virtual ProductVariant Variant { get; set; }
}