// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class RMG_Prod_Def_UnitType
{
    public int TC { get; set; }

    public string UnitTypID { get; set; }

    public string UnitTypeName { get; set; }

    public string ShortName { get; set; }

    public int? DecimalPlaces { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }
}