// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Sales_Customer
{
    public string CustomerID { get; set; }

    public string CustomerName { get; set; }

    public string CustomerCompany { get; set; }

    public string CustomerAddress { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public decimal? OpeningBalance { get; set; }

    public string ContatPerson1 { get; set; }

    public string Designation1 { get; set; }

    public string phone1 { get; set; }

    public string ContatPerson2 { get; set; }

    public string Designation2 { get; set; }

    public string phone2 { get; set; }

    public string ContatPerson3 { get; set; }

    public string Designation3 { get; set; }

    public string phone3 { get; set; }

    public decimal? CreditLImit { get; set; }

    public string FAX { get; set; }

    public string URL { get; set; }

    public string Email1 { get; set; }

    public string Email2 { get; set; }

    public string Email3 { get; set; }

    public string CustomerType { get; set; }

    public string Category { get; set; }

    public string SalesPersonID { get; set; }

    public string BIN { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }

    public string CustomerCode { get; set; }

    public string CountryId { get; set; }

    public string City { get; set; }

    public string StateOrProvince { get; set; }

    public string ZipCode { get; set; }

    public string VatRegNo { get; set; }

    public string Tin { get; set; }

    public string ContactPerson { get; set; }

    public string DevitOrCredit { get; set; }

    public DateTime? OpeningDate { get; set; }

    public string ShortName { get; set; }
}