// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Sales_ContactPerson
{
    public decimal AutoId { get; set; }

    public string CPID { get; set; }

    public string ContactPersonName { get; set; }

    public string DesignationCode { get; set; }

    public string ContactPersonMobile { get; set; }

    public string ContactPersonEmail { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }
}