// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Sales_DeliveryLocation
{
    public string DeliveryLocationCode { get; set; }

    public string CustomerID { get; set; }

    public string LocationAddress { get; set; }

    public string ContactPerson { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string DesignationCode { get; set; }

    public string CountryId { get; set; }

    public string city { get; set; }

    public string StateOrProvince { get; set; }

    public string ZipCode { get; set; }

    public string Remarks { get; set; }

    public string DeliveryCode { get; set; }

    public int AutoId { get; set; }
}