// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Sales_Def_PaymentTerms
{
    public string PaymentTermsCode { get; set; }

    public string PaymentTermsName { get; set; }

    public string Percentise { get; set; }

    public string Type { get; set; }

    public int? CreditDays { get; set; }

    public decimal TC { get; set; }
}