// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class SALES_Def_BankInfo
{
    public decimal AutoID { get; set; }

    public string BankID { get; set; }

    public string BankName { get; set; }

    public string ShortName { get; set; }

    public DateTime? LDate { get; set; }

    public string LUser { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }
}