// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class SalesLine
{
    public long LineID { get; set; }

    public long InvoiceID { get; set; }

    public int ProductID { get; set; }

    public int? VariantID { get; set; }

    public decimal Qty { get; set; }

    public decimal UnitPrice { get; set; }

    public decimal LineAmount { get; set; }

    public decimal? DiscountAmount { get; set; }

    public decimal NetLineAmount { get; set; }

    public virtual SalesInvoice Invoice { get; set; }

    public virtual Product Product { get; set; }

    public virtual ICollection<PromoApplication> PromoApplication { get; set; } = new List<PromoApplication>();

    public virtual ProductVariant Variant { get; set; }
}