// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Sales_Def_PaymentMode
{
    public string PaymentModeID { get; set; }

    public string PaymentModeName { get; set; }

    public string PaymentModeShortName { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }

    public int AutoId { get; set; }
}