// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Sales_Def_ImporterInfo
{
    public decimal TC { get; set; }

    public string ImporterID { get; set; }

    public string Name { get; set; }

    public string ShortName { get; set; }

    public string Address { get; set; }

    public string Remarks { get; set; }

    public string ContactPerson { get; set; }

    public string Designation { get; set; }

    public string Phone { get; set; }

    public string Email { get; set; }

    public string ContactPerson2 { get; set; }

    public string Designation2 { get; set; }

    public string Phone2 { get; set; }

    public string Email2 { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }
}