// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class SalesInvoice
{
    public long InvoiceID { get; set; }

    public string InvoiceNo { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public int? CustomerID { get; set; }

    public int WarehouseID { get; set; }

    public decimal TotalAmount { get; set; }

    public decimal DiscountAmount { get; set; }

    public decimal NetAmount { get; set; }

    public int? CreatedBy { get; set; }

    public string Note { get; set; }

    public virtual ICollection<PromoApplication> PromoApplication { get; set; } = new List<PromoApplication>();

    public virtual ICollection<SalesLine> SalesLine { get; set; } = new List<SalesLine>();
}