// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Sep_DocumentInfo
{
    public decimal autoId { get; set; }

    public string DocCode { get; set; }

    public string JobNo { get; set; }

    public string DocumentName { get; set; }

    public string DocumentDiscription { get; set; }

    public string DocumentType { get; set; }

    public byte[] Doucment { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string UserInfoEmployeeID { get; set; }
}