// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Sep_Documentation
{
    public decimal TC { get; set; }

    public string JobNo { get; set; }

    public string PrifixId { get; set; }

    public DateTime? Date { get; set; }

    public string LCNo { get; set; }

    public decimal? LCValue { get; set; }

    public string IPNo { get; set; }

    public DateTime? IPDate { get; set; }

    public string UndertakingNo { get; set; }

    public string InvoiceNo { get; set; }

    public string BillNo { get; set; }

    public string PONo { get; set; }

    public string ContainerNo { get; set; }

    public string MaterialDescription { get; set; }

    public decimal? Quntity1 { get; set; }

    public decimal? Quntity2 { get; set; }

    public string FWDR_ShippingAgent { get; set; }

    public string Vessel_RottNo { get; set; }

    public DateTime? ETA { get; set; }

    public DateTime? ETB { get; set; }

    public string BENo { get; set; }

    public DateTime? BEDate { get; set; }

    public DateTime? Un_StuffingLocationDate { get; set; }

    public DateTime? DateOfClearence { get; set; }

    public string ShipmentStatus { get; set; }

    public string Remarks { get; set; }

    public string LUser { get; set; }

    public DateTime? LDate { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public DateTime? ModifyDate { get; set; }

    public string CompanyCode { get; set; }

    public string EmployeeID { get; set; }

    public string Unit1 { get; set; }

    public string Unit2 { get; set; }

    public string SupplierId { get; set; }

    public string PortId { get; set; }

    public string PortNameId { get; set; }

    public string CustomerID { get; set; }

    public string CustomerAddress { get; set; }

    public DateTime? DocReceivedDate { get; set; }

    public DateTime? ATA { get; set; }

    public DateTime? ATB { get; set; }

    public decimal? TransportCost { get; set; }

    public string VehicleID { get; set; }

    public string Vehicle { get; set; }

    public string Vendor { get; set; }

    public string DocumentationId { get; set; }

    public string CurrencyId { get; set; }

    public string ConsoleNo { get; set; }

    public string ExpenseTypeID { get; set; }

    public bool? IsEdit { get; set; }

    public decimal? BDTRate { get; set; }

    public decimal? MinimumAgencyCom { get; set; }

    public decimal? CommOnInvoiceValue { get; set; }

    public string DeliveryLocationCode { get; set; }

    public DateTime? BLDate { get; set; }

    public DateTime? InvoiceDate { get; set; }

    public DateTime? LCDate { get; set; }

    public string DocumentTypeID { get; set; }

    public string HAWB { get; set; }

    public string MAWB { get; set; }

    public string LCANo { get; set; }

    public DateTime? Dischargedate { get; set; }

    public string ContainerSize { get; set; }

    public string IsCustomJobNo { get; set; }

    public string PlaceOfLoadingID { get; set; }

    public string ShedYardID { get; set; }

    public DateTime? ETDDate { get; set; }

    public string FreightCharge { get; set; }

    public string CustomerID_Importer { get; set; }

    public DateTime? DocumentHandoverDate { get; set; }

    public DateTime? CargoHandoverDate { get; set; }

    public string DepotID { get; set; }

    public string BookingConfirmationReference { get; set; }

    public string ImporterID { get; set; }

    public string ExporterID { get; set; }

    public decimal? PackingQuantity { get; set; }

    public string PackingUnitType { get; set; }

    public DateTime? ETACTGPORT { get; set; }

    public DateTime? SHIPARRIVEDDATE { get; set; }

    public decimal? InvoiceValue { get; set; }

    public string NameOfFreightForwarder { get; set; }

    public string AssessmentNo { get; set; }

    public string RNo { get; set; }

    public string ClientStationwiseSLNo { get; set; }

    public string ExpNo { get; set; }

    public DateTime? ExpDate { get; set; }

    public decimal? AssessableRate { get; set; }

    public decimal? AssessableValue { get; set; }

    public string InvoiceCurrencyID { get; set; }
}