// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace GCTL.Data.Models
{
    public partial class sp_GetCustomerReportsInfoResult
    {
        [StringLength(300)]
        public string CompanyName { get; set; }
        [StringLength(2147483647)]
        public string Address1 { get; set; }
        [StringLength(50)]
        public string CustomerID { get; set; }
        [StringLength(2147483647)]
        public string CustomerName { get; set; }
        [StringLength(200)]
        public string Address { get; set; }
        [StringLength(50)]
        public string Phone { get; set; }
        [StringLength(150)]
        public string FAX { get; set; }
        [StringLength(50)]
        public string Email { get; set; }
        [StringLength(50)]
        public string CustomerType { get; set; }
        [StringLength(4000)]
        public string ContactPersonDetails { get; set; }
    }
}
