// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class Statuses
{
    public int StatusID { get; set; }

    public string StatusName { get; set; }

    public string LIP { get; set; }

    public string LMAC { get; set; }

    public int? CreatedBy { get; set; }

    public int? UpdatedBy { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string StatusType { get; set; }

    public DateTime? DeletedAt { get; set; }

    public int? DeletedBy { get; set; }

    public virtual Employees CreatedByNavigation { get; set; }

    public virtual Employees DeletedByNavigation { get; set; }

    public virtual ICollection<EmployeeOfficeInfo> EmployeeOfficeInfo { get; set; } = new List<EmployeeOfficeInfo>();

    public virtual ICollection<EmployeeTransfer> EmployeeTransfer { get; set; } = new List<EmployeeTransfer>();

    public virtual ICollection<EmployeeTransferHistory> EmployeeTransferHistory { get; set; } = new List<EmployeeTransferHistory>();

    public virtual ICollection<Holidays> Holidays { get; set; } = new List<Holidays>();

    public virtual Employees UpdatedByNavigation { get; set; }
}