// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class TenantInfo
{
    public int Id { get; set; }

    public string TenantName { get; set; }

    public string Identifier { get; set; }

    public string ConnectionString { get; set; }

    public string Description { get; set; }

    public virtual ICollection<ApplicationRole> AspNetRoles { get; set; } = new List<ApplicationRole>();

    public virtual ICollection<ApplicationUser> AspNetUsers { get; set; } = new List<ApplicationUser>();

    public virtual ICollection<Organization> Organization { get; set; } = new List<Organization>();
}