// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class TimeFormats
{
    public int TimeFormatID { get; set; }

    public string FormatCode { get; set; }

    public string DisplayText { get; set; }

    public virtual ICollection<Localizations> Localizations { get; set; } = new List<Localizations>();
}