// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class UserVisitLogs
{
    public int Id { get; set; }

    public string UserId { get; set; }

    public string Path { get; set; }

    public string Method { get; set; }

    public string Lmac { get; set; }

    public string Ipaddress { get; set; }

    public DateTime VisitTime { get; set; }

    public double? DurationInSeconds { get; set; }
}