// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace GCTL.Data.Models;

public partial class VariantAttribute
{
    public int VariantID { get; set; }

    public int AttributeID { get; set; }

    public int AttributeValueID { get; set; }

    public virtual AttributeDef Attribute { get; set; }

    public virtual AttributeValue AttributeValue { get; set; }

    public virtual ProductVariant Variant { get; set; }
}